Tinybit.RGB_Car_Big(Tinybit.enColor.OFF)
Tinybit.RGB_Car_Program().clear()
Tinybit.RGB_Car_Program().show()
basic.forever(function () {
    music.playTone(196, music.beat(BeatFraction.Half))
    Tinybit.RGB_Car_Big(Tinybit.enColor.Green)
    Tinybit.RGB_Car_Program().showColor(neopixel.colors(NeoPixelColors.Red))
    Tinybit.RGB_Car_Program().show()
    music.playTone(196, music.beat(BeatFraction.Half))
    Tinybit.CarCtrlSpeed(Tinybit.CarState.Car_Run, 80)
    Tinybit.RGB_Car_Big(Tinybit.enColor.Blue)
    Tinybit.RGB_Car_Program().showColor(neopixel.colors(NeoPixelColors.Orange))
    Tinybit.RGB_Car_Program().show()
    music.playTone(262, music.beat(BeatFraction.Whole))
    Tinybit.RGB_Car_Big(Tinybit.enColor.White)
    Tinybit.RGB_Car_Program().showColor(neopixel.colors(NeoPixelColors.Yellow))
    Tinybit.RGB_Car_Program().show()
    music.playTone(262, music.beat(BeatFraction.Half))
    Tinybit.CarCtrlSpeed(Tinybit.CarState.Car_Back, 80)
    Tinybit.RGB_Car_Big(Tinybit.enColor.Cyan)
    Tinybit.RGB_Car_Program().showColor(neopixel.colors(NeoPixelColors.Green))
    Tinybit.RGB_Car_Program().show()
    music.playTone(294, music.beat(BeatFraction.Half))
    Tinybit.RGB_Car_Big(Tinybit.enColor.Pinkish)
    Tinybit.RGB_Car_Program().showColor(neopixel.colors(NeoPixelColors.Blue))
    Tinybit.RGB_Car_Program().show()
    music.playTone(262, music.beat(BeatFraction.Half))
    Tinybit.CarCtrlSpeed(Tinybit.CarState.Car_SpinLeft, 80)
    Tinybit.RGB_Car_Big(Tinybit.enColor.Yellow)
    Tinybit.RGB_Car_Program().showColor(neopixel.colors(NeoPixelColors.Indigo))
    Tinybit.RGB_Car_Program().show()
    music.playTone(247, music.beat(BeatFraction.Half))
    Tinybit.RGB_Car_Big(Tinybit.enColor.Red)
    Tinybit.RGB_Car_Program().showColor(neopixel.colors(NeoPixelColors.Violet))
    Tinybit.RGB_Car_Program().show()
    music.playTone(220, music.beat(BeatFraction.Whole))
    Tinybit.RGB_Car_Big(Tinybit.enColor.Green)
    Tinybit.RGB_Car_Program().showColor(neopixel.colors(NeoPixelColors.Purple))
    Tinybit.RGB_Car_Program().show()
    Tinybit.CarCtrlSpeed(Tinybit.CarState.Car_SpinLeft, 80)
    music.playTone(220, music.beat(BeatFraction.Whole))
    Tinybit.RGB_Car_Big(Tinybit.enColor.Blue)
    Tinybit.RGB_Car_Program().showColor(neopixel.colors(NeoPixelColors.White))
    Tinybit.RGB_Car_Program().show()
    music.rest(music.beat(BeatFraction.Whole))
    music.playTone(220, music.beat(BeatFraction.Half))
    Tinybit.CarCtrlSpeed(Tinybit.CarState.Car_SpinRight, 80)
    Tinybit.RGB_Car_Big(Tinybit.enColor.White)
    Tinybit.RGB_Car_Program().showColor(neopixel.colors(NeoPixelColors.Red))
    Tinybit.RGB_Car_Program().show()
    music.playTone(220, music.beat(BeatFraction.Half))
    Tinybit.RGB_Car_Big(Tinybit.enColor.Cyan)
    Tinybit.RGB_Car_Program().showColor(neopixel.colors(NeoPixelColors.Orange))
    Tinybit.RGB_Car_Program().show()
    music.playTone(294, music.beat(BeatFraction.Whole))
    Tinybit.CarCtrlSpeed(Tinybit.CarState.Car_Run, 80)
    Tinybit.RGB_Car_Big(Tinybit.enColor.Pinkish)
    Tinybit.RGB_Car_Program().showColor(neopixel.colors(NeoPixelColors.Yellow))
    Tinybit.RGB_Car_Program().show()
    music.playTone(294, music.beat(BeatFraction.Half))
    Tinybit.RGB_Car_Big(Tinybit.enColor.Yellow)
    Tinybit.RGB_Car_Program().showColor(neopixel.colors(NeoPixelColors.Green))
    Tinybit.RGB_Car_Program().show()
    music.playTone(330, music.beat(BeatFraction.Half))
    Tinybit.CarCtrlSpeed(Tinybit.CarState.Car_Back, 80)
    Tinybit.RGB_Car_Big(Tinybit.enColor.Red)
    Tinybit.RGB_Car_Program().showColor(neopixel.colors(NeoPixelColors.Blue))
    Tinybit.RGB_Car_Program().show()
    music.playTone(294, music.beat(BeatFraction.Half))
    Tinybit.RGB_Car_Big(Tinybit.enColor.Green)
    Tinybit.RGB_Car_Program().showColor(neopixel.colors(NeoPixelColors.Indigo))
    Tinybit.RGB_Car_Program().show()
    music.playTone(262, music.beat(BeatFraction.Half))
    Tinybit.CarCtrlSpeed(Tinybit.CarState.Car_SpinLeft, 80)
    Tinybit.RGB_Car_Big(Tinybit.enColor.Blue)
    Tinybit.RGB_Car_Program().showColor(neopixel.colors(NeoPixelColors.Violet))
    Tinybit.RGB_Car_Program().show()
    music.playTone(247, music.beat(BeatFraction.Whole))
    Tinybit.RGB_Car_Big(Tinybit.enColor.White)
    Tinybit.RGB_Car_Program().showColor(neopixel.colors(NeoPixelColors.Purple))
    Tinybit.RGB_Car_Program().show()
    music.playTone(196, music.beat(BeatFraction.Whole))
    Tinybit.CarCtrlSpeed(Tinybit.CarState.Car_SpinRight, 80)
    Tinybit.RGB_Car_Big(Tinybit.enColor.Cyan)
    Tinybit.RGB_Car_Program().showColor(neopixel.colors(NeoPixelColors.White))
    Tinybit.RGB_Car_Program().show()
    music.rest(music.beat(BeatFraction.Whole))
    music.playTone(196, music.beat(BeatFraction.Half))
    Tinybit.RGB_Car_Big(Tinybit.enColor.Pinkish)
    Tinybit.RGB_Car_Program().showColor(neopixel.colors(NeoPixelColors.Red))
    Tinybit.RGB_Car_Program().show()
    music.playTone(196, music.beat(BeatFraction.Half))
    Tinybit.CarCtrlSpeed(Tinybit.CarState.Car_Run, 80)
    Tinybit.RGB_Car_Big(Tinybit.enColor.Red)
    Tinybit.RGB_Car_Program().showColor(neopixel.colors(NeoPixelColors.Orange))
    Tinybit.RGB_Car_Program().show()
    music.playTone(330, music.beat(BeatFraction.Half))
    Tinybit.RGB_Car_Big(Tinybit.enColor.Green)
    Tinybit.RGB_Car_Program().showColor(neopixel.colors(NeoPixelColors.Green))
    Tinybit.RGB_Car_Program().show()
    music.playTone(349, music.beat(BeatFraction.Half))
    Tinybit.CarCtrlSpeed(Tinybit.CarState.Car_Back, 80)
    Tinybit.RGB_Car_Big(Tinybit.enColor.Blue)
    Tinybit.RGB_Car_Program().showColor(neopixel.colors(NeoPixelColors.Blue))
    Tinybit.RGB_Car_Program().show()
    music.playTone(330, music.beat(BeatFraction.Half))
    Tinybit.RGB_Car_Big(Tinybit.enColor.White)
    Tinybit.RGB_Car_Program().showColor(neopixel.colors(NeoPixelColors.Indigo))
    Tinybit.RGB_Car_Program().show()
    music.playTone(294, music.beat(BeatFraction.Half))
    Tinybit.CarCtrlSpeed(Tinybit.CarState.Car_SpinLeft, 80)
    Tinybit.RGB_Car_Big(Tinybit.enColor.Cyan)
    Tinybit.RGB_Car_Program().showColor(neopixel.colors(NeoPixelColors.Violet))
    Tinybit.RGB_Car_Program().show()
    music.playTone(262, music.beat(BeatFraction.Whole))
    Tinybit.RGB_Car_Big(Tinybit.enColor.Pinkish)
    Tinybit.RGB_Car_Program().showColor(neopixel.colors(NeoPixelColors.Purple))
    Tinybit.RGB_Car_Program().show()
    music.playTone(220, music.beat(BeatFraction.Whole))
    Tinybit.CarCtrlSpeed(Tinybit.CarState.Car_SpinRight, 80)
    Tinybit.RGB_Car_Big(Tinybit.enColor.Yellow)
    Tinybit.RGB_Car_Program().showColor(neopixel.colors(NeoPixelColors.White))
    Tinybit.RGB_Car_Program().show()
    music.rest(music.beat(BeatFraction.Whole))
    music.playTone(196, music.beat(BeatFraction.Half))
    Tinybit.RGB_Car_Big(Tinybit.enColor.Red)
    Tinybit.RGB_Car_Program().showColor(neopixel.colors(NeoPixelColors.Red))
    Tinybit.RGB_Car_Program().show()
    music.playTone(196, music.beat(BeatFraction.Half))
    Tinybit.CarCtrlSpeed(Tinybit.CarState.Car_Run, 80)
    Tinybit.RGB_Car_Big(Tinybit.enColor.Green)
    Tinybit.RGB_Car_Program().showColor(neopixel.colors(NeoPixelColors.Red))
    Tinybit.RGB_Car_Program().show()
    music.playTone(220, music.beat(BeatFraction.Half))
    Tinybit.RGB_Car_Big(Tinybit.enColor.Blue)
    Tinybit.RGB_Car_Program().showColor(neopixel.colors(NeoPixelColors.Orange))
    Tinybit.RGB_Car_Program().show()
    music.playTone(294, music.beat(BeatFraction.Half))
    Tinybit.CarCtrlSpeed(Tinybit.CarState.Car_Back, 80)
    Tinybit.RGB_Car_Big(Tinybit.enColor.White)
    Tinybit.RGB_Car_Program().showColor(neopixel.colors(NeoPixelColors.Orange))
    Tinybit.RGB_Car_Program().show()
    music.playTone(247, music.beat(BeatFraction.Half))
    Tinybit.RGB_Car_Big(Tinybit.enColor.Cyan)
    Tinybit.RGB_Car_Program().showColor(neopixel.colors(NeoPixelColors.Green))
    Tinybit.RGB_Car_Program().show()
    music.playTone(262, music.beat(BeatFraction.Whole))
    Tinybit.CarCtrlSpeed(Tinybit.CarState.Car_SpinLeft, 80)
    Tinybit.RGB_Car_Big(Tinybit.enColor.Pinkish)
    Tinybit.RGB_Car_Program().showColor(neopixel.colors(NeoPixelColors.Violet))
    Tinybit.RGB_Car_Program().show()
    basic.pause(2000)
})
